In [2]:
import pandas as pd

In [14]:
df = pd.read_csv("Data/Data_Folder/updated-animal-data-farm-id-70.csv")
df.head()

C:\Users\rashe\AppData\Local\Temp\ipykernel_16540\2847240147.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Data/Data_Folder/updated-animal-data-farm-id-70.csv")

,datetime,event,temp,airTemp,humidity,accel,rumination,ageInDays,aveHerdTemp,date,time,id,THI,rumination_per_day
0,2025-01-16 19:16:31,NaN,39.1,2.7,67.5,0.22,0,10,39.125,2025-01-16,19:16:31,6255,40.66,45
1,2025-01-16 19:31:31,NaN,39.1,2.4,70.4,0.33,0,10,39.125,2025-01-16,19:31:31,6255,39.87,45
2,2025-01-16 19:46:31,NaN,39.2,2.4,70.4,0.19,0,10,39.125,2025-01-16,19:46:31,6255,39.87,45
3,2025-01-16 20:01:33,NaN,39.1,2.4,72.5,0.32,0,10,39.125,2025-01-16,20:01:33,6255,39.62,45
4,2025-01-16 20:16:33,NaN,39.1,2.5,74.2,0.15,0,10,39.125,2025-01-16,20:16:33,6255,39.57,45

In [15]:
df['id'].unique()

array([6255, 6257, 6259, 6261, 6263, 6265, 6267, 6299, 6301, 6303],
      dtype=int64)

In [ ]:
df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")

df = df.sort_values("datetime")

start_date = pd.Timestamp("2025-09-01")
end_date = pd.Timestamp("2025-10-31 23:59:59")  

filtered_df = df[(df["datetime"] >= start_date) & (df["datetime"] <= end_date) & (df["id"] == 6255)]

In [17]:
cols_to_drop = ['event', 'date', 'time']  # drop irrevelant columns :)
df_filtered = filtered_df.drop(columns=[col for col in cols_to_drop if col in filtered_df.columns])

output_path = 'Data/Test/Test-animal-id-6255-farm-Id-70.csv' 
df_filtered.to_csv(output_path, index=False)

print(f"File saved to {output_path}")

File saved to Data/Test/Test-animal-id-6255-farm-Id-70.csv

In [3]:
import pandas as pd

input_path = 'Data/Data_Folder/new-animal-data-farm-id-66-2025-10-27-to-2025-11-19.csv'
df = pd.read_csv(input_path)

In [4]:
cols_to_drop = ['event', 'date', 'time']  # drop irrevelant columns :)
df = df.drop(columns=[col for col in cols_to_drop if col in df.columns])
df.to_csv('Data/Test/new-farm-66.csv', index=False)

In [5]:
df.head()

,datetime,temp,airTemp,humidity,accel,rumination,ageInDays,aveHerdTemp,id,THI,rumination_per_day
0,2025-10-27 0:04,39.2,7.5,65.8,0.26,0,389,39.000,753,47.86,90
1,2025-10-27 0:19,39.0,7.5,65.8,0.19,0,389,38.900,753,47.86,90
2,2025-10-27 0:34,37.3,7.2,63.5,0.23,0,389,38.625,753,47.59,90
3,2025-10-27 0:49,38.7,7.2,64.9,0.10,0,389,39.000,753,47.49,90
4,2025-10-27 1:04,39.0,7.2,66.4,0.10,0,389,39.125,753,47.38,90